---
- name: unms - start
  community.docker.docker_container:
    name: unms
    image: "{{ unms_image }}"
    pull: true
    ports:
      - "2055:2055/udp"
    env:
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/unms/config:/config"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.unms.rule: "HostRegexp(`unms(.{{ inventory__homelab_domain }})?`)"
      traefik.http.routers.unms.entrypoints: "websecure"
      traefik.http.routers.unms.tls: "true"
      traefik.http.services.unms.loadbalancer.server.port: "443"
      traefik.http.services.unms.loadbalancer.server.scheme: "https"
    restart_policy: unless-stopped
    state: started
  tags: unms
