---
- name: include util_resource_facts.yml
  ansible.builtin.include_tasks: util_resources_facts.yml

- name: start
  when:
    - pve_resource_exists
    - pve_resource_exists[0].status != 'running'
  block:
    - name: "{{ hostname }} - Start"
      ansible.builtin.command: >
        qm start {{ vmid }}
      changed_when: true
      when: resource_type == 'vm'

    - name: "{{ hostname }} - Start"
      ansible.builtin.command: >
        pct start {{ vmid }}
      changed_when: true
      when: resource_type == 'ct'

    - name: "{{ hostname }} - Wait for SSH port become available"
      ansible.builtin.wait_for:
        host: "{{ net_ip }}"
        port: 22
