---
- name: Install packages
  ansible.builtin.package:
    update_cache: true
    state: present
    name:
      - openssh-server

- name: Enable and start service
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started

- name: Add authorized keys
  ansible.posix.authorized_key:
    user: "{{ sshd_authorized_keys_user }}"
    state: present
    key: "{{ item }}"
  loop: "{{ sshd_authorized_keys }}"
  no_log: true
  notify: restart ssh
  when: sshd_authorized_keys_add

- name: Set sshd_config params
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: /usr/sbin/sshd -T -f %s
  loop:
    - { regexp: "^#?Port", line: "Port {{ sshd_port }}" }
    - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin {{ sshd_permit_root_login }}" }
    - { regexp: "^#?LoginGraceTime", line: "LoginGraceTime 20" }
    - { regexp: "^#?MaxAuthTries", line: "MaxAuthTries 3" }
    - { regexp: "^#?ClientAliveInterval", line: "ClientAliveInterval 300" }
    - { regexp: "^#?PubkeyAuthentication", line: "PubkeyAuthentication yes" }
    - { regexp: "^#?PasswordAuthentication", line: "PasswordAuthentication {{ sshd_password_authentication }}" }
    - { regexp: "^#?PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "^#?AuthenticationMethods", line: "AuthenticationMethods {{ sshd_authentication_methods }}" }
    - { regexp: "^#?X11Forwarding", line: "X11Forwarding no" }
  notify: restart ssh
