---
- name: Provision host
  hosts: spsrv
  gather_facts: no

  vars:
    resource_type: vm
    vmid: 112
    hostname: dev
    comment: Development
    vm_image: /mnt/pve/spsrv-proxmox/template/qcow2/ubuntu-20.04-server-cloudimg-amd64.img
    cores: 4
    mem: 4096
    disk_size: 30
    net_ip: 192.168.10.12
    net_vlan: 10
    net_gw: 192.168.10.1
    net_dns: 192.168.10.1
    net_domain: "{{ inventory__homelab_domain }}"
    vm_other_options: >
      --onboot 1

  roles:
    - { role: pve_manager }
    - { role: portainer_api }


- name: Pre-configure host
  hosts: dev
  gather_facts: yes

  pre_tasks:
    - name: Wait for cloud-init to finish
      ansible.builtin.wait_for:
        path: /var/lib/cloud/instance/boot-finished

    - name: Set timezone
      community.general.timezone:
        name: Europe/Moscow
      become: true

    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
      become: true


# - name: Apply common roles
#   hosts: dev
#   gather_facts: no

#   roles:
#     - { role: common/packages, become: true }
#     - { role: spirkaa.zsh_prezto }
#     - { role: spirkaa.nano }
#     - { role: common/motd, become: true }
#     - { role: common/sshd, become: true }
#     - { role: common/docker, become: true }


- name: Apply host-specific roles
  hosts: dev
  gather_facts: no

  vars:
    gitea_ssh_user: ubuntu

  roles:
    - { role: homelab_svc/dev, become: true, tags: [dev, svc] }
