---
- hosts: proxmox
  gather_facts: yes

  vars:
    snmp_syslocation: krs

  roles:
    - { role: pve/common, tags: [pve, pve_common] }
    - { role: common/packages, tags: [pve, pve_packages] }
    - { role: spirkaa.zsh_prezto, tags: [pve, pve_zsh] }
    - { role: spirkaa.nano, tags: [pve, pve_nano] }
    - { role: common/motd, tags: [pve, pve_motd] }
    - { role: common/sshd, tags: [pve, pve_sshd] }
    - { role: pve/kernel_modules, tags: [pve, pve_kernel_modules] }
    - { role: pve/nut, tags: [pve, pve_nut] }
    - { role: pve/postfix, tags: [pve, pve_postfix] }
    - { role: pve/rclone, tags: [pve, pve_rclone] }
    - { role: pve/rsnapshot, tags: [pve, pve_rsnapshot] }
    - { role: pve/telegraf, tags: [pve, pve_telegraf] }
    - { role: common/snmp, tags: [pve, pve_snmp] }
    - { role: pve/snmp_extend, tags: [pve, pve_snmp] }
    - { role: pve/smartd, tags: [pve, pve_smartd] }
    - { role: pve/storage, tags: [pve, pve_storage] }
    - { role: common/wireguard, tags: [pve, pve_wireguard] }
