---
- name: Download VM templates
  hosts: proxmox
  gather_facts: false

  vars:
    template_image_url:
      - https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64.img
      - https://cdimage.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2
    template_image_path: /mnt/pve/spsrv-proxmox/template/qcow2

  tasks:
    - name: template image
      run_once: true
      block:
        - name: template image - download
          ansible.builtin.get_url:
            url: "{{ item }}"
            dest: "{{ template_image_path }}/{{ item | basename }}"
            mode: 0644
            force: true
          loop: "{{ template_image_url }}"

        - name: template image - install qemu-guest-agent
          ansible.builtin.command: >
            virt-customize -a {{ template_image_path }}/{{ item | basename }}
              --install qemu-guest-agent
          changed_when: true
          loop: "{{ template_image_url }}"

        - name: template image - reset machine-id
          ansible.builtin.command: >
            virt-customize -a {{ template_image_path }}/{{ item | basename }}
              --run-command "echo -n > /etc/machine-id"
          changed_when: true
          loop: "{{ template_image_url }}"
