---
roles:
  - name: spirkaa.nano
  - name: spirkaa.zsh_prezto
  - name: geerlingguy.pip
  - name: geerlingguy.docker

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
  - name: community.network
  - name: serverscom.mitogen
