---
- name: Apply host-specific roles
  hosts: vps
  gather_facts: true

  vars:
    sshd_port: 51858
    sshd_password_authentication: 'no'
    sshd_authentication_methods: publickey

  roles:
    # - { role: common/packages, tags: [vps, packages] }
    # - { role: spirkaa.zsh_prezto, tags: [vps, zsh] }
    # - { role: spirkaa.nano, tags: [vps, nano] }
    # - { role: common/motd, tags: [vps, motd] }
    # - { role: common/sshd, tags: [vps, sshd] }
    # - { role: common/snmp, tags: [vps, snmp] }
    # - { role: common/docker, tags: [vps, docker] }
    - { role: vps, tags: [vps, vps_specific] }
    - role: sing_box
      when: sing_box_enabled | default(false) | bool
      tags:
        - vps
        - sing_box
    - role: xray
      when: xray_enabled | default(false) | bool
      tags:
        - vps
        - xray

  pre_tasks:
    - name: Set timezone
      community.general.timezone:
        name: Europe/Moscow

    - name: Set DNS in resolv.conf
      ansible.builtin.copy:
        content: |
          nameserver 1.1.1.1
          nameserver 1.0.0.1
        dest: /etc/resolv.conf
        mode: "0644"
        owner: root
        group: root

    - name: Set DNS in dhclient.conf
      ansible.builtin.lineinfile:
        path: /etc/dhcp/dhclient.conf
        line: supersede domain-name-servers 1.1.1.1, 1.0.0.1;
        state: present
