---
- name: influxdb - create dir
  ansible.builtin.file:
    path: "{{ app_path }}/influxdb/config"
    state: directory
    recurse: true
  tags: [influxdb, grafana]

- name: influxdb - copy files
  ansible.builtin.copy:
    src: files/influxdb.conf
    dest: "{{ app_path }}/influxdb/config"
    mode: 0644
  notify: influxdb - restart
  tags: [influxdb, grafana]

- name: influxdb - start
  community.docker.docker_container:
    name: influxdb
    image: "{{ influxdb_image }}"
    image_name_mismatch: recreate
    pull: true
    ports:
      - "2003:2003"
      - "8086:8086"
    volumes:
      - "{{ app_path }}/influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
      - "{{ app_path }}/influxdb/db:/var/lib/influxdb"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.influxdb.rule: "HostRegexp(`influxdb(.{{ inventory__homelab_domain }})?`)"
      traefik.http.services.influxdb.loadbalancer.server.port: "8086"
      traefik.http.routers.influxdb.entrypoints: "websecure"
      traefik.http.routers.influxdb.tls: "true"
    restart_policy: unless-stopped
    state: started
  register: influxdb_start
  tags: [influxdb, grafana]
