---
- name: loki - create dir
  ansible.builtin.file:
    path: "{{ app_path }}/loki/data"
    state: directory
    recurse: true
  tags: [loki, grafana]

- name: loki - get data dir ownership
  ansible.builtin.stat:
    path: "{{ app_path }}/loki/data"
  register: loki_data
  tags: [loki, grafana]

- name: loki - set data dir ownership  # noqa: no-free-form
  ansible.builtin.command: >
    chown -R 10001:10001 {{ app_path }}/loki/data
  changed_when: true
  when: loki_data.stat.uid != 10001 or loki_data.stat.gid != 10001
  tags: [loki, grafana]

- name: loki - start
  community.docker.docker_container:
    name: loki
    image: "{{ loki_image }}"
    pull: true
    ports:
      - "3100:3100"
    volumes:
      - "{{ app_path }}/loki/data:/loki"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.loki.rule: "HostRegexp(`loki{fqdn:(.{{ app_base_domain }})?}`)"
      traefik.http.services.loki.loadbalancer.server.port: "3100"
      traefik.http.routers.loki.entrypoints: "websecure"
      traefik.http.routers.loki.tls: "true"
    command: -config.file=/etc/loki/local-config.yaml
    restart_policy: unless-stopped
    state: started
  tags: [loki, grafana]
