---
- name: mosquitto - create dir
  ansible.builtin.file:
    path: "{{ app_path }}/mosquitto/config"
    state: directory
    recurse: true
  tags: mosquitto

- name: mosquitto - copy files
  ansible.builtin.copy:
    src: files/mosquitto.conf
    dest: "{{ app_path }}/mosquitto/config"
    owner: "1883"
    group: "1883"
    mode: "0777"
  notify: mosquitto - restart
  tags: mosquitto

- name: mosquitto - start
  community.docker.docker_container:
    name: mosquitto
    image: "{{ mosquitto_image }}"
    image_name_mismatch: recreate
    pull: true
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "{{ app_path }}/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "{{ app_path }}/mosquitto/data:/mosquitto/data"
      - "{{ app_path }}/mosquitto/log:/mosquitto/log"
    networks:
      - name: traefik
    networks_cli_compatible: true
    restart_policy: unless-stopped
    state: started
  register: mosquitto_start
  tags: mosquitto
