---
- name: prometheus - create dir
  ansible.builtin.file:
    path: "{{ app_path }}/prometheus/{{ item }}"
    state: directory
    recurse: true
  loop:
    - "config"
    - "data"
  tags: [prometheus, grafana]

- name: prometheus - copy files
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ app_path }}/prometheus/config/prometheus.yml"
    mode: "0644"
  notify: prometheus - restart
  tags: [prometheus, grafana]

- name: prometheus - get data dir ownership
  ansible.builtin.stat:
    path: "{{ app_path }}/prometheus/data"
  register: prometheus_data
  tags: [prometheus, grafana]

- name: prometheus - set data dir ownership  # noqa: no-free-form
  ansible.builtin.command: >
    chown -R 65534:65534 {{ app_path }}/prometheus/data
  changed_when: true
  when: prometheus_data.stat.uid != 65534 or prometheus_data.stat.gid != 65534
  tags: [prometheus, grafana]

- name: prometheus - start
  community.docker.docker_container:
    name: prometheus
    image: "{{ prometheus_image }}"
    pull: true
    volumes:
      - "{{ app_path }}/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ app_path }}/prometheus/data:/prometheus"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: "HostRegexp(`prometheus(.{{ app_base_domain }})?`)"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"
      traefik.http.routers.prometheus.entrypoints: "websecure"
      traefik.http.routers.prometheus.tls: "true"
    restart_policy: unless-stopped
    state: started
  register: prometheus_start
  tags: [prometheus, grafana]
