#!/bin/sh

PATH=$PATH:/bin:/usr/bin/:/usr/local/bin/:/usr/local/sbin

`which sudo` `which ipmitool` sensor \
| awk -v hostname=$(hostname) -F'|' 'tolower($3) ~ /(volt|rpm|watt|degree)/ && $2 !~ /na/ {
    if (tolower($3) ~ /volt/) type="voltage";
    if (tolower($3) ~ /rpm/)  type="fan";
    if (tolower($3) ~ /watt/) type="power";
    if (tolower($3) ~ /degree/) type="temperature";
    if (tolower($3) ~ /watts/) type="power";
    if (tolower($3) ~ /units/) type="current";
    gsub(/[ \t]*$/,"",$1);
    gsub(/[ ]/,"\\ ",$1);
    gsub(/,/,"\\,", $1);
    print "ipmi,host="hostname",type="type",instance="$1" value="sprintf("%.4f",$2);
}'
