---
- name: Install packages
  ansible.builtin.package:
    state: present
    name:
      - figlet

- name: Delete /etc/motd
  ansible.builtin.file:
    path: /etc/motd
    state: absent

- name: Create update-motd.d dir
  ansible.builtin.file:
    path: /etc/update-motd.d
    state: directory
    recurse: true

- name: Copy files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/update-motd.d"
    mode: "0755"
    directory_mode: "0755"
  loop:
    - 00-header
    - 90-footer

- name: Copy 10-sysinfo
  ansible.builtin.template:
    src: 10-sysinfo.j2
    dest: /etc/update-motd.d/10-sysinfo
    mode: "0755"
  when: ansible_distribution == "Debian" or ansible_virtualization_type == "lxc"

- name: Remove unwanted motd blocks
  ansible.builtin.file:
    path: /etc/update-motd.d/{{ item }}
    state: absent
  loop:
    - 10-help-text
    - 50-motd-news
  when: ansible_distribution == "Ubuntu"
