---
- name: bazarr - start
  community.docker.docker_container:
    name: bazarr
    image: "{{ bazarr_image }}"
    pull: true
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/bazarr/config:/config"
      - "{{ app_path }}/data/downloads:/downloads"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.bazarr.rule: "HostRegexp(`bazarr(.{{ inventory__homelab_domain }})?`)"
      traefik.http.services.bazarr.loadbalancer.server.port: "6767"
      traefik.http.routers.bazarr.entrypoints: "websecure"
      traefik.http.routers.bazarr.tls: "true"
    restart_policy: unless-stopped
    state: started
  tags: bazarr
