---
- name: flaresolverr - start
  community.docker.docker_container:
    name: flaresolverr
    image: "{{ flaresolverr_image }}"
    pull: true
    env:
      TZ: "{{ tz }}"
      LOG_LEVEL: "info"
      LOG_HTML: "false"
      CAPTCHA_SOLVER: "none"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.flaresolverr.rule: "HostRegexp(`flaresolverr(.{{ inventory__homelab_domain }})?`)"
      traefik.http.services.flaresolverr.loadbalancer.server.port: "8191"
      traefik.http.routers.flaresolverr.entrypoints: "websecure"
      traefik.http.routers.flaresolverr.tls: "true"
    restart_policy: unless-stopped
    state: started
  tags: flaresolverr
