---
- name: monitorrent - create dir
  ansible.builtin.file:
    path: "{{ app_path }}/monitorrent/config"
    state: directory
    recurse: true
  tags: monitorrent

- name: monitorrent - touch db
  ansible.builtin.file:
    path: "{{ app_path }}/monitorrent/config/monitorrent.db"
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: "0644"
  tags: monitorrent

- name: monitorrent - start
  community.docker.docker_container:
    name: monitorrent
    image: "{{ monitorrent_image }}"
    pull: true
    env:
      TZ: "{{ tz }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ app_path }}/monitorrent/config/monitorrent.db:/var/www/monitorrent/monitorrent.db"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.monitorrent.rule: "HostRegexp(`monitorrent(.{{ inventory__homelab_domain }})?`)"
      traefik.http.services.monitorrent.loadbalancer.server.port: "6687"
      traefik.http.routers.monitorrent.entrypoints: "websecure"
      traefik.http.routers.monitorrent.tls: "true"
    restart_policy: unless-stopped
    state: started
  tags: monitorrent
