---
- name: muximux - start
  community.docker.docker_container:
    name: muximux
    image: "{{ muximux_image }}"
    pull: true
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/muximux/config:/config"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.muximux.rule: "HostRegexp(`spnas(.{{ inventory__homelab_domain }})?`)"
      traefik.http.routers.muximux.entrypoints: "websecure"
      traefik.http.routers.muximux.tls: "true"
    restart_policy: unless-stopped
    state: started
  register: muximux_start
  tags: muximux

- name: muximux - delete old front-end
  ansible.builtin.file:
    state: absent
    path: "{{ muximux_www }}"
  notify: muximux - restart
  when: muximux_start.changed
  tags: muximux

- name: Force all notified handlers
  ansible.builtin.meta: flush_handlers
  tags: muximux

- name: muximux - wait for settings.ini.php-example
  ansible.builtin.wait_for:
    path: "{{ muximux_www }}/muximux/settings.ini.php-example"
    state: present
    timeout: 30
  when: muximux_start.changed
  tags: muximux

- name: muximux - copy files
  ansible.builtin.template:
    src: settings.ini.php.j2
    dest: "{{ muximux_www }}/muximux/settings.ini.php"
    owner: "{{ puid }}"
    group: "{{ pgid }}"
    mode: 0664
  notify: muximux - restart
  tags: muximux
