---
main_storage_path: /mnt/storage
zfs_path: /mnt/tank0/ds0
nfs_export_path: /srv/nfs

parity_disks:
  - { src: /dev/disk/by-id/ata-ST20000NM007D-3DJ103_ZVT66SEP-part1, path: /mnt/parity/parity00, fs: xfs, opts: defaults, content: false }

data_disks:
  - { src: /dev/disk/by-id/ata-WDC_WUH721818ALE6L4_5DH2YXJJ-part1, path: /mnt/data/disk00, fs: xfs, opts: defaults, content: true }
  - { src: /dev/disk/by-id/ata-WUH721818ALE6L4_4MG51P8H-part1, path: /mnt/data/disk10, fs: xfs, opts: defaults, content: true }
  - { src: /dev/disk/by-id/ata-WDC_WUH721818ALE6L4_3RG84LBA-part1, path: /mnt/data/disk20, fs: xfs, opts: defaults, content: false }
  - { src: /dev/disk/by-id/ata-ST20000NM007D-3DJ103_ZVT655WP-part1, path: /mnt/data/disk30, fs: xfs, opts: defaults, content: false }

extra_mountpoints:
  - { path: "{{ main_storage_path }}" }
  - { src: "{{ main_storage_path }}/downloads", path: "{{ nfs_export_path }}/downloads", fs: none, opts: "bind,_netdev,x-systemd.requires=/mnt/storage", state: mounted }
  - { src: "{{ zfs_path }}/proxmox", path: "{{ nfs_export_path }}/proxmox", fs: none, opts: "bind,_netdev,x-systemd.requires=zfs-mount.service", state: mounted }
  - { src: "{{ zfs_path }}/cloud", path: "{{ nfs_export_path }}/cloud", fs: none, opts: "bind,_netdev,x-systemd.requires=zfs-mount.service", state: mounted }
  - { src: "{{ zfs_path }}/src", path: "{{ nfs_export_path }}/src", fs: none, opts: "bind,_netdev,x-systemd.requires=zfs-mount.service", state: mounted }

# zfs_disks:
#   - ata-WDC_WD120EMFZ-11A6JA0_Z2KAEX5T
#   - ata-WDC_WD120EMFZ-11A6JA0_Z2KJR39T

# retired_disks:
#   - { src: /dev/disk/by-id/ata-HGST_HUH721008ALE604_1SGNMJ4Z-part1, path: /mnt/parity/parity01, fs: ext4, opts: defaults, state: absent, content: false }
#   - { src: /dev/disk/by-id/ata-HGST_HUH721008ALE604_1SGSUYPZ-part1, path: /mnt/parity/parity02, fs: ext4, opts: defaults, state: absent, content: false }
#   - { src: /dev/disk/by-id/ata-HGST_HUH721008ALE604_1SGN507Z-part1, path: /mnt/data/disk05, fs: ext4, opts: defaults, state: absent, content: false }
#   - { src: /dev/disk/by-id/ata-HGST_HUH721008ALE604_7JKK8PRC-part1, path: /mnt/data/disk06, fs: ext4, opts: defaults, state: absent, content: false }
#   - { src: /dev/disk/by-id/ata-HGST_HUH721008ALE604_1SGRYMDZ-part1, path: /mnt/data/disk03, fs: ext4, opts: defaults, state: absent, content: false }
#   - { src: /dev/disk/by-id/ata-HGST_HUH721008ALE604_1SGAJ19Z-part1, path: /mnt/data/disk04, fs: ext4, opts: defaults, state: absent, content: false }
#   - { src: /dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_2SGEZJ8N-part1, path: /mnt/data/disk01, fs: ext4, opts: defaults, state: absent, content: false }
#   - { src: /dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_1EHUH8NZ-part1, path: /mnt/data/disk02, fs: ext4, opts: defaults, state: absent, content: false }
#   - { src: /dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_1EHVUJKZ-part1, path: /mnt/data/disk07, fs: ext4, opts: defaults, state: absent, content: false }
#   - { src: /dev/disk/by-id/ata-WDC_WD80EMAZ-00WJTA0_7HK0X5ZN-part1, path: /mnt/data/disk08, fs: ext4, opts: defaults, state: absent, content: false }

fstab_mergerfs:
  - src: /mnt/data/*
    path: "{{ main_storage_path }}"
    fs: fuse.mergerfs
    opts: defaults,noforget,inodecalc=path-hash,cache.files=off,moveonenospc=true,category.create=pfrd,dropcacheonclose=true,minfreespace=250G,fsname=mergerfs

nfs_exports:
  - "{{ nfs_export_path }} 10.10.20.0/24(ro,fsid=0,no_subtree_check)"
  - "{{ nfs_export_path }} 192.168.20.0/24(ro,fsid=0,no_subtree_check)"
  - "{{ nfs_export_path }}/proxmox 10.10.20.0/24(rw,fsid=1,no_root_squash,no_subtree_check)"
  - "{{ nfs_export_path }}/proxmox 192.168.20.0/24(rw,fsid=1,no_root_squash,no_subtree_check)"
  - "{{ nfs_export_path }}/downloads 10.10.20.0/24(rw,fsid=2,root_squash,all_squash,no_subtree_check,anonuid=1000,anongid=1000)"
  - "{{ nfs_export_path }}/cloud 10.10.20.0/24(rw,fsid=3,root_squash,all_squash,no_subtree_check,anonuid=1000,anongid=1000)"
  - "{{ nfs_export_path }}/src 10.10.20.0/24(rw,fsid=4,root_squash,all_squash,no_subtree_check,anonuid=1000,anongid=1000)"

mergerfs_version: "2.40.2"
mergerfs_package_name: mergerfs_{{ mergerfs_version }}.debian-bookworm_amd64.deb
mergerfs_package_url: https://github.com/trapexit/mergerfs/releases/download/{{ mergerfs_version }}/{{ mergerfs_package_name }}

snapraid_version: "12.2"
snapraid_package_name: snapraid_{{ snapraid_version }}-1_amd64.deb

snapraid_bin_path: /usr/local/bin/snapraid
snapraid_config_path: /etc/snapraid.conf
snapraid_delete_threshold: 50
snapraid_touch: true

snapraid_log_path: /var/log/snapraid.log
snapraid_log_size: 5000

snapraid_run_scrub: true
snapraid_run_scrub_plan: 12
snapraid_run_scrub_age: 10

snapraid_email_sendon: error
snapraid_email_address_to: "{{ inventory__admin_mail }}"

snapraid_smtp_host: "{{ inventory__smtp_host }}"
snapraid_smtp_port: "{{ inventory__smtp_port }}"
snapraid_smtp_tls: true
snapraid_smtp_username: "{{ inventory__smtp_username }}"
snapraid_smtp_password: "{{ inventory__smtp_password }}"

snapraid_run_repo: https://github.com/Chronial/snapraid-runner.git
snapraid_run_version: 60b8b67
snapraid_run_dest: /opt/snapraid-runner
snapraid_run_path: "{{ snapraid_run_dest }}/snapraid-runner"
snapraid_run_conf: "{{ snapraid_run_path }}.conf"
snapraid_run_bin: "{{ snapraid_run_path }}.py"

snapraid_cron_jobs:
  - name: snapraid_runner
    job: python3 {{ snapraid_run_bin }} -c {{ snapraid_run_conf }} > /dev/null 2>&1 && curl -fsS --retry 3 {{ inventory__healthchecksio_url }}/spsrv-snapraid-runner > /dev/null 2>&1
    weekday: "*"
    hour: "01"
