---
- name: esphome - create dir
  ansible.builtin.file:
    path: "{{ esphome_config_path }}/components"
    state: directory
    recurse: true
  tags: esphome

- name: esphome - copy files
  ansible.builtin.copy:
    src: files/components
    dest: "{{ esphome_config_path }}"
    mode: "0644"
    directory_mode: "0755"
  # notify: esphome - restart
  tags: esphome

- name: esphome - copy files
  ansible.builtin.template:
    src: esphome/{{ item.src }}
    dest: "{{ esphome_config_path }}/{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: secrets.yaml.j2, dest: secrets.yaml }
    - { src: ble-tracker.yaml.j2, dest: ble-tracker.yaml }
    - { src: .local-haier.yaml.j2, dest: .local-haier.yaml }
    - { src: haier-ac01.yaml.j2, dest: haier-ac01.yaml }
    - { src: haier-ac02.yaml.j2, dest: haier-ac02.yaml }
    - { src: haier-ac03.yaml.j2, dest: haier-ac03.yaml }
    - { src: killawatt-dacha.yaml.j2, dest: killawatt-dacha.yaml }
  # notify: esphome - restart
  tags: esphome

- name: esphome - start
  community.docker.docker_container:
    name: esphome
    image: "{{ esphome_image }}"
    image_name_mismatch: recreate
    pull: true
    env:
      ESPHOME_DASHBOARD_USE_PING: "true"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ esphome_config_path }}:/config"
    network_mode: host
    restart_policy: unless-stopped
    state: started
  register: esphome_start
  tags: esphome
