---
- name: homeassistant - create dir
  ansible.builtin.file:
    path: "{{ homeassistant_config_path }}"
    state: directory
    recurse: true
  tags: homeassistant

- name: homeassistant - copy files
  ansible.builtin.template:
    src: homeassistant/{{ item.src }}
    dest: "{{ homeassistant_config_path }}/{{ item.dest }}"
    mode: 0644
  loop:
    - { src: configuration.yaml.j2, dest: configuration.yaml }
    - { src: groups.yaml.j2, dest: groups.yaml }
    - { src: lights.yaml.j2, dest: lights.yaml }
    - { src: secrets.yaml.j2, dest: secrets.yaml }
    - { src: yeelight.yaml.j2, dest: yeelight.yaml }
  notify: homeassistant - restart
  tags: homeassistant

- name: homeassistant - start
  community.docker.docker_container:
    name: homeassistant
    image: "{{ homeassistant_image }}"
    image_name_mismatch: recreate
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ homeassistant_config_path }}:/config"
    network_mode: host
    restart_policy: unless-stopped
    state: started
  register: homeassistant_start
  tags: homeassistant
