---
- name: mergerfs - check if installed
  ansible.builtin.command: >
    dpkg-query -W mergerfs
  ignore_errors: true
  register: mergerfs_is_installed
  changed_when: mergerfs_is_installed.rc != 0

- name: mergerfs - download and install package
  when: mergerfs_version not in mergerfs_is_installed.stdout
  block:
    - name: mergerfs - download package
      ansible.builtin.get_url:
        url: "{{ mergerfs_package_url }}"
        dest: /tmp/{{ mergerfs_package_name }}
        mode: "0644"

    - name: mergerfs - install package
      ansible.builtin.apt:
        deb: /tmp/{{ mergerfs_package_name }}
        state: present

- name: mergerfs - mount array
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    state: present
  with_items:
    - "{{ fstab_mergerfs }}"
