---
- name: mount - create dirs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items:
    - "{{ parity_disks }}"
    - "{{ data_disks }}"
    - "{{ extra_mountpoints }}"

- name: mount - configure fstab
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ parity_disks }}"
    - "{{ data_disks }}"
    - "{{ extra_mountpoints }}"
  when: item.path != main_storage_path
