---
- name: nfs - install packages
  ansible.builtin.package:
    state: present
    name:
      - nfs-common
      - nfs-kernel-server

- name: nfs - ensure directories to export exist
  ansible.builtin.file:
    path: "{{ item.strip().split()[0] }}"
    state: directory
    mode: 0777
  with_items: "{{ nfs_exports }}"

- name: nfs - copy config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: exports.j2, dest: /etc/exports }
  notify: nfs - re-export

- name: nfs - ensure service is running
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: true
  when: nfs_exports | length
