---
- name: snapraid - install package
  ansible.builtin.package:
    state: present
    name:
      - snapraid

- name: snapraid - copy configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0664"
  loop:
    - { src: snapraid.conf.j2, dest: /etc/snapraid.conf }

- name: snapraid-runner - clone repo
  ansible.builtin.git:
    repo: "{{ snapraid_run_repo }}"
    dest: "{{ snapraid_run_dest }}"
    version: "{{ snapraid_run_version }}"

- name: snapraid-runner - copy configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0664"
  loop:
    - { src: snapraid-runner.conf.j2, dest: "{{ snapraid_run_conf }}" }

- name: snapraid-runner - setup cron job
  ansible.builtin.cron:
    user: "{{ item.user | default('root') }}"
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default('*') | string }}"
    minute: "{{ item.minute | default('00') | string }}"
    hour: "{{ item.hour | default('00') | string }}"
    dom: "{{ item.dom | default('*') | string }}"
    disabled: "{{ item.disabled | default(false) }}"
  loop: "{{ snapraid_cron_jobs }}"
  no_log: true
