---
- name: create transcode tmpfs volume
  community.docker.docker_volume:
    volume_name: transcode
    driver_options:
      type: tmpfs
      device: tmpfs
      o: size=3000m
    state: present
  tags: [jellyfin, plex]

- name: jellyfin
  ansible.builtin.include_tasks: jellyfin.yml
  tags: jellyfin

- name: plex
  ansible.builtin.include_tasks: plex.yml
  tags: plex

# - name: tautulli
#   ansible.builtin.include_tasks: tautulli.yml
#   tags: tautulli

# - name: ombi
#   ansible.builtin.include_tasks: ombi.yml
#   tags: ombi

# - name: airvideohd
#   ansible.builtin.include_tasks: airvideohd.yml
#   tags: airvideohd
