---
- name: ombi - start
  community.docker.docker_container:
    name: ombi
    image: "{{ ombi_image }}"
    pull: true
    ports:
      - "3579:3579"
    env:
      PUID: "{{ puid | string }}"
      PGID: "{{ pgid | string }}"
      TZ: "{{ tz }}"
      HTTP_PROXY: "{{ inventory__http_proxy }}"
      HTTPS_PROXY: "{{ inventory__http_proxy }}"
      NO_PROXY: ".home.devmem.ru,plex,{{ inventory__http_proxy_no }}"
    volumes:
      - "{{ app_path }}/ombi/config:/config"
    restart_policy: unless-stopped
    state: started
  tags: ombi
