---
- name: Install packages
  ansible.builtin.package:
    state: present
    name:
      - sudo
      - lm-sensors
      - smartmontools

- name: Tasks for specific hosts
  when: inventory_hostname == "spsrv" or inventory_hostname == "spmaxi"
  block:
    - name: Install packages
      ansible.builtin.package:
        state: present
        name:
          - ipmitool

    - name: Copy telegraf_ipmi script
      ansible.builtin.copy:
        src: files/telegraf_ipmi
        dest: /usr/local/bin
        mode: 0755

- name: Tasks for specific hosts
  when: inventory_hostname == "spsrv"
  block:
    - name: Install packages
      ansible.builtin.package:
        state: present
        name:
          - hddtemp

    - name: Copy hddtemp config generator
      ansible.builtin.copy:
        src: files/hddtemp_systemd_gen
        dest: /usr/local/bin/hddtemp_systemd_gen
        mode: 0755
      register: hddtemp_cfg

    - name: Creaty systemd dir
      ansible.builtin.file:
        path: /usr/lib/systemd/system
        state: directory
        mode: 0755

    - name: Configure hddtemp
      ansible.builtin.shell: >
        /usr/local/bin/hddtemp_systemd_gen > /usr/lib/systemd/system/hddtemp.service
      changed_when: true
      when: hddtemp_cfg.changed
      notify: restart hddtemp

- name: Copy sudoers.d file
  ansible.builtin.copy:
    src: files/telegraf_sudo
    dest: /etc/sudoers.d
    mode: 0440

- name: Check whether telegraf is installed
  ansible.builtin.command: >
    dpkg-query -W telegraf
  ignore_errors: true
  register: telegraf_is_installed
  changed_when: telegraf_is_installed.rc != 0

- name: Download and install package
  when: telegraf_agent_version not in telegraf_is_installed.stdout
  block:
    - name: Download telegraf package
      ansible.builtin.get_url:
        url: "{{ telegraf_agent_url }}"
        dest: /tmp/{{ telegraf_agent_package }}
        mode: 0644

    - name: Install telegraf package
      ansible.builtin.apt:
        deb: /tmp/{{ telegraf_agent_package }}
        state: present

- name: Copy telegraf.conf
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: 0644
  notify: restart telegraf
