---
- name: code - start
  community.docker.docker_container:
    name: code
    image: "{{ code_image }}"
    pull: true
    ports:
      - "8443:8443"
    env:
      PUID: "{{ puid | string }}"
      PGID: "{{ pgid | string }}"
      TZ: "{{ tz }}"
      PASSWORD: "{{ code_pass }}"
      SUDO_PASSWORD: "{{ code_pass }}"
      DOCKER_MODS: "linuxserver/mods:code-server-docker|linuxserver/mods:code-server-python3"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ dev_app_path }}/code/config:/config"
    restart_policy: unless-stopped
    state: started
  no_log: true
  tags: code
