---
- name: antifilter - create directory
  ansible.builtin.file:
    path: /opt/antifilter
    state: directory
    mode: "0700"

- name: antifilter - copy files
  ansible.builtin.copy:
    src: files/antifilter.sh
    dest: "{{ vps_antifilter_path }}"
    mode: "0700"

- name: antifilter - create a cron job
  ansible.builtin.cron:
    name: antifilter
    minute: "*/30"
    user: root
    job: "{{ vps_antifilter_path }}"
    cron_file: ansible_antifilter
