---
- name: bird - install packages
  ansible.builtin.package:
    state: present
    name:
      - bird

- name: bird - create files
  ansible.builtin.file:
    path: "{{ vps_bird_config_path }}/{{ item }}"
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: "0644"
  loop:
    - allyouneed.txt

- name: bird - copy configuration
  ansible.builtin.template:
    src: bird.conf.j2
    dest: "{{ vps_bird_config_path }}/bird.conf"
    owner: bird
    group: bird
    mode: "0640"
  notify: restart bird
