---
- name: cadvisor - create network
  community.docker.docker_network:
    name: "{{ app_network_name }}"
  tags: cadvisor

- name: cadvisor - start
  community.docker.docker_container:
    name: cadvisor
    image: "{{ cadvisor_image }}"
    image_name_mismatch: recreate
    pull: true
    ports:
      - "18080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    command: >
      --docker_only=true
      --store_container_labels=false
      --whitelisted_container_labels=""
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: false
    labels:
      traefik.enable: "true"
      traefik.docker.network: "{{ app_network_name }}"
      traefik.http.routers.cadvisor.rule: "HostRegexp(`{{ inventory_hostname_short }}(.{{ app_base_domain }})?`) && PathPrefix(`/metrics`)"
      traefik.http.services.cadvisor.loadbalancer.server.port: "8080"
      traefik.http.routers.cadvisor.entrypoints: "websecure"
      traefik.http.routers.cadvisor.tls: "true"
    restart_policy: unless-stopped
    state: started
  tags: cadvisor
