---
- name: Create docker.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: true

- name: Copy daemon.json
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker
    mode: "0644"
  notify: Restart docker service

- name: Copy override.conf
  ansible.builtin.copy:
    src: files/override.conf
    dest: /etc/systemd/system/docker.service.d
    mode: "0644"
  notify: Restart docker service
