---
- name: Configure APT sources list
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: "0644"
  notify: Update APT cache
  become: true
  when: >
    ansible_facts.distribution == "Debian" and ansible_facts.distribution_major_version | int < 13
    or ansible_facts.distribution == "Ubuntu" and ansible_facts.distribution_major_version | int < 26

- name: Configure APT sources list
  ansible.builtin.template:
    src: "{{ ansible_facts.distribution | lower }}.sources.j2"
    dest: /etc/apt/sources.list.d/{{ ansible_facts.distribution | lower }}.sources
    mode: "0644"
  notify: Update APT cache
  become: true
  when: >
    ansible_facts.distribution == "Debian" and ansible_facts.distribution_major_version | int >= 13
    or ansible_facts.distribution == "Ubuntu" and ansible_facts.distribution_major_version | int >= 26

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
