---
- name: dnscrypt-proxy2 | Install package
  community.general.opkg:
    name: dnscrypt-proxy2
    state: present

- name: dnscrypt-proxy2 | Enable DNS servers
  ansible.builtin.lineinfile:
    path: /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
    regexp: "^(# )?server_names ="
    line: "server_names = ['google', 'cloudflare', 'scaleway-fr', 'dct-ru', 'nextdns']"
  notify:
    - Reload dnscrypt-proxy

- name: dnscrypt-proxy2 | Configure dnsmasq
  uci:
    command: set
    config: dhcp
    section: "@dnsmasq[-1]"
    value:
      noresolv: 1
  notify:
    - Uci commit
    - Reload dnsmasq

- name: dnscrypt-proxy2 | Configure dnsmasq - forward server
  uci:
    command: add_list
    config: dhcp
    section: "@dnsmasq[-1]"
    option: server
    value: 127.0.0.53#53
    unique: true
  notify:
    - Uci commit
    - Reload dnsmasq
