---
- name: getdomains | Copy script
  ansible.builtin.template:
    src: getdomains.j2
    dest: /etc/init.d/getdomains
    mode: "0755"
  notify:
    - Run getdomains script

- name: getdomains | Create simplink in rc.d
  ansible.builtin.file:
    src: /etc/init.d/getdomains
    dest: /etc/rc.d/S99getdomains
    state: link

- name: getdomains | Add cron job
  ansible.builtin.lineinfile:
    path: /etc/crontabs/root
    line: "0 4 * * * /etc/init.d/getdomains start"
    owner: root
    group: root
    mode: "0644"
    create: true
    state: present

- name: getdomains | Enable and start cron
  ansible.builtin.service:
    name: cron
    state: started
    enabled: true
