---
- name: node-exporter | Install package
  community.openwrt.opkg:
    name: "{{ openwrt_node_exporter_packages | join(',') }}"
    state: present
  notify:
    - Restart node-exporter

- name: node-exporter | Configure service
  community.openwrt.uci:
    command: set
    config: prometheus-node-exporter-lua
    section: main
    value:
      listen_interface: lan
  notify:
    - Uci commit
    - Restart node-exporter
