---
- name: Install packages
  ansible.builtin.package:
    update_cache: true
    state: present
    name:
      - wireguard

- name: Enable kernel module
  community.general.modprobe:
    name: wireguard
    state: present

- name: Install wg-json
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/WireGuard/wireguard-tools/master/contrib/json/wg-json
    dest: /usr/local/bin/wg-json
    mode: "0755"
    force: true
  register: _download_result
  retries: 60
  delay: 1
  until: _download_result is not failed

- name: Enable packet forwarding
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/99-ip-forward.conf
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    reload: true
    state: present
